import AuthProvider from "@/context/AuthProvider"
import "../globals.css"
import { Toaster } from "@/components/ui/toaster"
import { Inter } from "next/font/google";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider >
      <body className={inter.className}>{children}
        <Toaster />
      </body>
      </AuthProvider>
    </html>
  )
}
